let data = [
	{
		fullName: "Leon Chung",
		status: "paid",
		dueDate: "20/09/2021",
		amountDue: 550.0,
		receipt_id: "1",
		billFrom: {
			streetAddress: "19 Union Terrace",
			city: "London",
			postalCode: "M5T 1B3",
			country: "United Kingdom",
		},
		billTo: {
			clientName: "King Bob",
			clientEmail: "kingbob@me.ca",
			clientStreetAddress: "bob street",
			clientCity: "Bob City",
			clientCountry: "Bob Country",
			clientPostalCode: "K1N B0B",
			invoiceDate: "03/24/23",
			projectDescription: "Testing invoice app",
		},
		invoiceItemList: [
			{
				itemName: "Banner Design",
				itemQuantity: 1,
				itemPrice: (50.99).toFixed(2),
				priceTotal: (50.99).toFixed(2),
			},
			{
				itemName: "Email Design",
				itemQuantity: 1,
				itemPrice: (100.5).toFixed(2),
				priceTotal: (100.5).toFixed(2),
			},
		],
	},
	{
		fullName: "king bob",
		status: "pending",
		dueDate: "10/08/2021",
		amountDue: 1550.3,
		receipt_id: "2",
	},
	{
		fullName: "queen stuart",
		status: "draft",
		dueDate: "29/12/2021",
		amountDue: 5540.99,
		receipt_id: "3",
	},
	{
		fullName: "Leon Chung",
		status: "paid",
		dueDate: "20/09/2021",
		amountDue: 550.0,
		receipt_id: "4",
	},
	{
		fullName: "king bob",
		status: "pending",
		dueDate: "10/08/2021",
		amountDue: 1550.3,
		receipt_id: "5",
	},
	{
		fullName: "queen stuart",
		status: "paid",
		dueDate: "29/12/2021",
		amountDue: 5540.99,
		receipt_id: "6",
	},
	{
		fullName: "Leon Chung",
		status: "paid",
		dueDate: "20/09/2021",
		amountDue: 550.0,
		receipt_id: "7",
	},
	{
		fullName: "king bob",
		status: "pending",
		dueDate: "10/08/2021",
		amountDue: 1550.3,
		receipt_id: "8",
	},
	{
		fullName: "queen stuart",
		status: "paid",
		dueDate: "29/12/2021",
		amountDue: 5540.99,
		receipt_id: "9",
	},
];

export { data };
